main: me.brunorm.chunk.ChunkFall
version: 0.3.2.1.1
name: ChunkFall
author: BrunoRM
softdepend:
  - Vault
  - WorldEdit
  - PlaceholderAPI
  - HolographicDisplays
  - DecentHolograms
api-version: 1.13

commands:
  chunkfall:
    description: Main command.